### ISSUE TITLE
상호작용 버튼 오류 수정

### ISSUE THREAD

**Issue by EricSupergene** [bakedpiig/Altar#58]
inventory\[invenIdx\] != null 로 선택한 아이템이 존재할 때만 아이템의 종류 판단해서 고치기
Player.cs(159, 163)

**Comment by SCOUTgit** [comment]
inventory[invenIdx] != null 로 선택한 아이템이 존재할 때만 아이템의 종류 판단해서 버튼 오류 수정하기
